CREATE TABLE SUCURSAL (
COD_SUCURSAL CHAR(2) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_SUCURSAL PRIMARY KEY(COD_SUCURSAL) 
);

CREATE TABLE USUARIO(
COD_USUARIO CHAR(2) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
USER VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
COD_SUCURSAL CHAR(2) NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY(COD_USUARIO),
CONSTRAINT FK_SUCURSAL FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL)
);

CREATE TABLE PRODUCTO (
COD_PRODUCTO CHAR(2) NOT NULL, 
NOMBRE VARCHAR(50) NOT NULL, 
PRECIO DECIMAL(10,2) NOT NULL, 
CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_PRODUCTO), 
CONSTRAINT CHK_PRODUCTO_PRECIO CHECK(PRECIO>0)
);